# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate the residuals for a VARMA model
#'
#' @export
varmaResiduals <- function(zt, Ph0, PH, TH, p, q, include_mean, beta) {
    .Call('_MTS_varmaResiduals', PACKAGE = 'MTS', zt, Ph0, PH, TH, p, q, include_mean, beta)
}

